### ISSUE TITLE
Problem installing on Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [konsalex/gatsby-wordpress-migrate#4]
Can't install using Yarn.

![image](https://user-images.githubusercontent.com/24384996/51229302-e5e55b80-1981-11e9-87cd-df585c78baa3.png)

**Comment by dimitrisraptis96** [comment]
Just added the package on **Windows 10** successfully! Please, follow the issue template and provide your **environment** along with your **package.json** in order to reproduce the issue.

**Comment by konsalex** [comment]
Hey @Suleman-Elahi . @dimitrisraptis96 is right, help us reproduce this problem with more information.

Some potential issues I can see are : 

1.  You are installing in a dir that contains special characters and yarn is breaking.
2. You are installing in the root directory and not in a directory containing a node project.
3. Have you tried Git BASH instead of CMD? 

Also, you can run `gatsby info --clipboard` in your project directory and paste the output here in order to help us check your system. 
Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`.

**Comment by konsalex** [comment]
You solved it @Suleman-Elahi ? 

If yes do you mind posting how in order to prevent further issues?

**Comment by konsalex** [comment]
Hey @Suleman-Elahi thank you for posting your output to the CLI. Could you pm me your XML in order to test it locally and find the problem cause as it seems you found a bug 🗡  .

You can send the XML through twitter or at konsalexee@gmail.com .

**Comment by Suleman-Elahi** [comment]
Done !!

**Comment by konsalex** [comment]
Hey @Suleman-Elahi . Just checked your XML.
The error is in the XML format. It has the whole post inside the Title tag!

**Comment by Suleman-Elahi** [comment]
Thanks. I think that i must have done something wrong while importing the XML from WordPress.
